# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: rag-sharepoint
metadata:
  template: rag-sharepoint@0.0.1-beta

# Infrastructure configuration
infra:
  provider: bicep
  path: infra
  module: main

services:
  rag-functions:
    project: ./app
    language: py
    host: function

# Pipeline configuration for CI/CD
pipeline:
  provider: github
